version: '3.8'
services:
  mcpx:
    image: us-central1-docker.pkg.dev/prj-common-442813/mcpx/mcpx:latest
    container_name: mcpx
    ports:
      - "19000:9000"
      - "13000:3000"
    volumes:
      - ./:/mcpx/packages/mcpx-server/config

  mcpx-ui:
    image: us-central1-docker.pkg.dev/prj-common-442813/mcpx/mcpx-ui:latest
    container_name: mcpx-ui
    ports:
      - "19001:9001"
      - "15173:5173"
