services:
  mcpx:
    image: us-central1-docker.pkg.dev/prj-common-442813/mcpx/mcpx:latest
    container_name: mcpx
    platform: linux/amd64
    ports:
      - "19000:9000"
      - "13000:3000"
    volumes:
      - ./:/mcpx/packages/mcpx-server/config

  mcpx-ui:
    image: us-central1-docker.pkg.dev/prj-common-442813/mcpx/mcpx-ui:latest
    container_name: mcpx-ui
    platform: linux/amd64
    ports:
      - "9001:9001"
      - "5173:5173"
    # command: ["sh", "-c", "npm run start:ui & wait"]
    # command: ["sh", "-c", "npm run start:webserver & VITE_WS_URL=ws://localhost:19001 VITE_API_SERVER_URL=http://localhost:19001 npm run start:ui & wait"]
